/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateUrlDto {

  /**
   * The original URL to be shorten
   */
  originalUrl: string;
}
