/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UrlStatsDto {
  shortCode: string;
  originalUrl: string;
  clickCount: number;
  createdAt: Date;
}
