/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UrlResponseDto {
  shortCode: string;
  shortUrl: string;
  originalUrl: string;
  createdAt: Date;
}
