/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UrlStatsDto } from '../../models/url-stats-dto';

export interface UrlControllerGetUrlStats$Params {

/**
 * Short code of the URL
 */
  shortCode: string;
}

export function urlControllerGetUrlStats(http: HttpClient, rootUrl: string, params: UrlControllerGetUrlStats$Params, context?: HttpContext): Observable<StrictHttpResponse<UrlStatsDto>> {
  const rb = new RequestBuilder(rootUrl, urlControllerGetUrlStats.PATH, 'get');
  if (params) {
    rb.path('shortCode', params.shortCode, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UrlStatsDto>;
    })
  );
}

urlControllerGetUrlStats.PATH = '/api/urls/stats/{shortCode}';
