/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface UrlControllerDeleteUrl$Params {

/**
 * Short code to delete
 */
  shortCode: string;
}

export function urlControllerDeleteUrl(http: HttpClient, rootUrl: string, params: UrlControllerDeleteUrl$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, urlControllerDeleteUrl.PATH, 'delete');
  if (params) {
    rb.path('shortCode', params.shortCode, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

urlControllerDeleteUrl.PATH = '/api/urls/delete/{shortCode}';
