/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { redirectControllerIgnoreFavicon } from '../fn/redirect/redirect-controller-ignore-favicon';
import { RedirectControllerIgnoreFavicon$Params } from '../fn/redirect/redirect-controller-ignore-favicon';
import { redirectControllerRedirect } from '../fn/redirect/redirect-controller-redirect';
import { RedirectControllerRedirect$Params } from '../fn/redirect/redirect-controller-redirect';

@Injectable({ providedIn: 'root' })
export class RedirectApi extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `redirectControllerIgnoreFavicon()` */
  static readonly RedirectControllerIgnoreFaviconPath = '/favicon.ico';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `redirectControllerIgnoreFavicon()` instead.
   *
   * This method doesn't expect any request body.
   */
  redirectControllerIgnoreFavicon$Response(params?: RedirectControllerIgnoreFavicon$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return redirectControllerIgnoreFavicon(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `redirectControllerIgnoreFavicon$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  redirectControllerIgnoreFavicon(params?: RedirectControllerIgnoreFavicon$Params, context?: HttpContext): Observable<void> {
    return this.redirectControllerIgnoreFavicon$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `redirectControllerRedirect()` */
  static readonly RedirectControllerRedirectPath = '/{shortCode}';

  /**
   * Redirect to the original URL using a short code.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `redirectControllerRedirect()` instead.
   *
   * This method doesn't expect any request body.
   */
  redirectControllerRedirect$Response(params: RedirectControllerRedirect$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return redirectControllerRedirect(this.http, this.rootUrl, params, context);
  }

  /**
   * Redirect to the original URL using a short code.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `redirectControllerRedirect$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  redirectControllerRedirect(params: RedirectControllerRedirect$Params, context?: HttpContext): Observable<void> {
    return this.redirectControllerRedirect$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
